import { expect, type Page } from "@playwright/test";
import {
  confirmCreditCostIfShown,
  generateDraftFromPreview,
} from "../helpers/credits";

export class MeetingBriefPage {
  constructor(private readonly page: Page) {}

  async goto() {
    await this.page.goto("/brief");
  }

  async expectLoaded() {
    await expect(this.page.getByRole("heading", { level: 1, name: "Meeting Brief" })).toBeVisible();
    await expect(this.page.getByTestId("meeting-brief-page")).toBeVisible();
  }

  async generateBrief() {
    const generated = this.page.waitForResponse(
      (r) => r.url().includes("/api/chat/brief") && r.request().method() === "POST"
    );
    await this.page.getByTestId("generate-brief-button").click();
    await confirmCreditCostIfShown(this.page);
    await generated;
    await expect(this.page.getByTestId("generated-brief")).toBeVisible();
  }

  async draftFollowUpEmail() {
    await this.page.getByTestId("draft-follow-up-button").click();
    await expect(this.page.getByRole("dialog")).toBeVisible();
    await expect(
      this.page.getByRole("heading", { name: "Follow-up email draft" })
    ).toBeVisible();
    const generated = this.page.waitForResponse(
      (r) =>
        r.url().includes("/api/monitor/draft-email") &&
        r.request().method() === "POST"
    );
    await generateDraftFromPreview(this.page);
    await generated;
    await expect(this.page.getByRole("dialog").locator("pre")).toBeVisible();
  }

  async expectAutoGeneratedBrief() {
    const generated = this.page.getByTestId("generated-brief");
    await expect(
      this.page.getByTestId("credit-confirm").or(generated).first()
    ).toBeVisible({ timeout: 15_000 });
    await confirmCreditCostIfShown(this.page);
    await expect(generated).toBeVisible({ timeout: 15_000 });
  }
}
