import { test, expect } from "./fixtures/base";
import { waitForSuccessfulApiResponse } from "./helpers/api";
import { fulfillJson } from "./helpers/network";

/**
 * The core adviser journey: every page a working adviser touches, plus the
 * flagship flows (proactive meeting prep, AI copilot, alerts triage, and
 * document ingestion). The console-error fixture makes each navigation a
 * regression check for free.
 */

test.describe("core adviser journey", () => {
  test("dashboard loads with KPIs and today's digest", async ({ app, page }) => {
    await waitForSuccessfulApiResponse(page, "/api/monitor/pulse", () => app.dashboard.goto());
    await app.dashboard.expectLoaded();
    await app.dashboard.expectKpisVisible();
    await app.dashboard.expectDigestVisible();
    await expect(page.getByTestId("priority-timeline")).toBeVisible();
  });

  test("navigation reaches every page without console errors", async ({ app }) => {
    await app.dashboard.goto();
    await app.dashboard.expectLoaded();

    await app.shell.navigateTo("AI Copilot");
    await app.aiCopilot.expectLoaded();

    await app.shell.navigateTo("Clients");
    await app.clients.expectLoaded();

    await app.shell.navigateTo("Meeting Brief");
    await app.meetingBrief.expectLoaded();

    await app.shell.navigateTo("Alerts");
    await app.alerts.expectLoaded();

    await app.shell.navigateTo("Ingestion");
    await app.ingestion.expectLoaded();

    await app.shell.navigateTo("Settings");
    await app.settings.expectLoaded();

    await app.shell.navigateTo("Dashboard");
    await app.dashboard.expectLoaded();
  });

  test("prepare-for-meeting deep link auto-generates a brief", async ({
    app,
    page,
  }) => {
    await app.dashboard.goto();
    await app.dashboard.expectLoaded();
    await app.dashboard.clickFirstPrepareBrief();
    await expect(page).toHaveURL(/\/brief\?clientId=c1&auto=1/);
    await app.meetingBrief.expectLoaded();
    await app.meetingBrief.expectAutoGeneratedBrief();
  });

  test("meeting brief generates and drafts a follow-up email", async ({
    app,
    page,
  }) => {
    await app.meetingBrief.goto();
    await app.meetingBrief.expectLoaded();
    await app.meetingBrief.generateBrief();

    await app.meetingBrief.draftFollowUpEmail();
    const dialog = page.getByRole("dialog");
    await expect(dialog.locator("pre")).toContainText(/Dear Alan/i);
    await dialog.getByTestId("modal-footer-close").click();
  });

  test("AI copilot holds a multi-turn conversation that survives reload", async ({
    app,
    page,
  }) => {
    await app.aiCopilot.goto();
    await app.aiCopilot.expectLoaded();
    await app.aiCopilot.ask("Which clients have unused ISA allowance?");
    await app.aiCopilot.ask("And which of those have the most cash?");
    expect(await app.aiCopilot.answerCount()).toBe(2);
    const conversationId = await app.aiCopilot.storedConversationId();
    expect(conversationId).toBeTruthy();

    // The thread re-renders from the persisted conversation, not a fresh chat.
    await page.reload();
    await app.aiCopilot.expectLoaded();
    await expect(app.aiCopilot.lastAnswer).toBeVisible();
    await expect(
      app.aiCopilot.userBubble("Which clients have unused ISA allowance?")
    ).toBeVisible();
    expect(await app.aiCopilot.storedConversationId()).toBe(conversationId);
  });

  test("clients list opens a client 360 view", async ({ app, page }) => {
    await app.clients.goto();
    await app.clients.expectLoaded();
    await app.clients.expectAnalyticsVisible();
    await app.clients.openFirstClient();
    await app.clients.expectDetailLoaded();
    await expect(page.getByTestId("client-intelligence")).toBeVisible();
    await expect(page.getByTestId("next-best-actions")).toBeVisible();
  });

  test("alerts draft an email and prep a brief", async ({ app, page }) => {
    await app.alerts.goto();
    await app.alerts.expectLoaded();

    await page.getByRole("button", { name: "Draft email" }).first().click();
    const dialog = page.getByRole("dialog");
    await expect(dialog).toBeVisible();
    await dialog.getByTestId("modal-footer-close").click();

    await app.alerts.clickPrepBriefOnFirstRow();
    await app.meetingBrief.expectAutoGeneratedBrief();
  });

  test("documents upload and transcripts ingest", async ({ app, page }) => {
    await app.ingestion.goto();
    await app.ingestion.expectLoaded();
    await waitForSuccessfulApiResponse(page, "/api/ingest/upload", () =>
      app.ingestion.uploadSampleDocument()
    );

    await waitForSuccessfulApiResponse(page, "/api/ingest/transcript", () =>
      app.ingestion.ingestTranscript(
        "Met with the client today. They confirmed their pension contribution increase and we agreed to review protection cover before the next annual review."
      )
    );
  });

  test("settings shows workspace posture and the AI audit log", async ({ app }) => {
    await app.settings.goto();
    await app.settings.expectLoaded();
    await app.settings.expectPostureVisible();
    await app.settings.expectAuditLogVisible();
  });

  test("a failing API degrades to an error state and recovers on retry", async ({
    app,
    page,
  }) => {
    let failNext = true;
    await page.route("**/api/monitor/pulse*", async (route) => {
      if (failNext) {
        await fulfillJson(route, 500, { detail: "Internal error" });
        return;
      }
      await route.fallback();
    });

    await app.dashboard.goto();
    const errorState = page.getByRole("alert").filter({ hasText: /wrong|error/i }).first();
    await expect(errorState).toBeVisible();

    // Recovery: the retry affordance refetches and the dashboard loads.
    failNext = false;
    await page.getByRole("button", { name: "Try again" }).first().click();
    await app.dashboard.expectLoaded();
  });
});
