import { test, expect } from "./fixtures/base";
import { waitForSuccessfulApiResponse } from "./helpers/api";
import { captureScreenshot } from "./helpers/screenshots";

test.describe("adviser QA journey", () => {
  test("dashboard digest, KPIs, and priority timeline", async ({ app, page }, testInfo) => {
    await Promise.all([
      page.waitForResponse(
        (r) => r.url().includes("/api/monitor/pulse") && r.ok()
      ),
      app.dashboard.goto(),
    ]);
    await captureScreenshot(page, "01-dashboard-before", testInfo);
    await app.dashboard.expectLoaded();
    await app.dashboard.expectKpisVisible();
    await app.dashboard.expectDigestVisible();
    await expect(page.getByTestId("digest-content-text")).toBeVisible();
    await expect(page.getByTestId("priority-timeline")).toBeVisible();
    await captureScreenshot(page, "02-dashboard-with-digest", testInfo);
  });

  test("prepare-for-meeting deep link from dashboard", async ({ app, page }, testInfo) => {
    await app.dashboard.goto();
    await app.dashboard.expectLoaded();
    await captureScreenshot(page, "03-before-prepare-deep-link", testInfo);
    await app.dashboard.clickFirstPrepareBrief();
    await expect(page).toHaveURL(/\/brief\?clientId=c1&auto=1/);
    await app.meetingBrief.expectLoaded();
    await app.meetingBrief.expectAutoGeneratedBrief();
    await captureScreenshot(page, "04-after-prepare-auto-brief", testInfo);
  });

  test("meeting brief follow-up email draft", async ({ app, page }, testInfo) => {
    await app.meetingBrief.goto();
    await app.meetingBrief.expectLoaded();
    await app.meetingBrief.generateBrief();
    await captureScreenshot(page, "05-brief-before-follow-up", testInfo);
    await app.meetingBrief.draftFollowUpEmail();
    const dialog = page.getByRole("dialog");
    await expect(dialog.locator("pre")).toContainText(/Dear Alan/i);
    await captureScreenshot(page, "06-brief-follow-up-modal", testInfo);
    await dialog.getByTestId("modal-footer-close").click();
  });

  test("clients list and client 360 detail", async ({ app, page }, testInfo) => {
    await app.dashboard.goto();
    await app.shell.navigateTo("Clients");
    await app.clients.expectLoaded();
    await app.clients.expectAnalyticsVisible();
    await captureScreenshot(page, "07-clients-list", testInfo);
    await app.clients.openFirstClient();
    await app.clients.expectDetailLoaded();
    await expect(page.getByTestId("client-prepare-button")).toBeVisible();
    await expect(page.getByTestId("client-ask-button")).toBeVisible();
    await expect(page.getByTestId("client-intelligence")).toBeVisible();
    await expect(page.getByTestId("next-best-actions")).toBeVisible();
    await captureScreenshot(page, "08-client-detail", testInfo);
  });

  test("edit client details", async ({ app, page }) => {
    await page.goto("/clients/c1");
    await app.clients.expectDetailLoaded();
    await app.clients.editClientName("Alan & Lynne Partridge (updated)");
    // Modal closes on a successful save (asserted inside editClientName).
    await expect(page.getByTestId("client-edit-button")).toBeVisible();
  });

  test("generate client review note", async ({ app, page }) => {
    await page.goto("/clients/c1");
    await app.clients.expectDetailLoaded();
    await app.clients.openReviewNote();
    await expect(page.getByTestId("review-note-content")).toContainText("Consumer Duty");
  });

  test("apply a playbook to a client", async ({ app, page }) => {
    await page.goto("/clients/c1");
    await app.clients.expectDetailLoaded();
    await expect(page.getByTestId("playbooks-card")).toBeVisible();
    await waitForSuccessfulApiResponse(page, "/apply-playbook", () =>
      app.clients.applyPlaybook("annual_review")
    );
  });

  test("multi-turn copilot conversation keeps a thread", async ({ app }) => {
    await app.aiCopilot.goto();
    await app.aiCopilot.expectLoaded();
    await app.aiCopilot.ask("Which clients have unused ISA allowance?");
    await app.aiCopilot.ask("And which of those have the most cash?");
    // Both turns remain on screen — the conversation thread is preserved.
    expect(await app.aiCopilot.answerCount()).toBe(2);
  });

  test("client-scoped AI copilot via deep link", async ({ app, page }, testInfo) => {
    await page.goto("/chat?clientId=c1");
    await app.aiCopilot.expectLoaded();
    await expect(page.getByTestId("copilot-client-filter")).toHaveValue("c1");
    await captureScreenshot(page, "09-copilot-scoped-before", testInfo);
    await app.aiCopilot.askScopedQuestion();
    await captureScreenshot(page, "10-copilot-scoped-answer", testInfo);
  });

  test("alerts prep brief and draft email", async ({ app, page }, testInfo) => {
    await app.alerts.goto();
    await app.alerts.expectLoaded();
    await captureScreenshot(page, "11-alerts-table", testInfo);
    await page.getByRole("button", { name: "Draft email" }).first().click();
    const dialog = page.getByRole("dialog");
    await expect(dialog).toBeVisible();
    await captureScreenshot(page, "12-alerts-draft-email-modal", testInfo);
    await dialog.getByTestId("modal-footer-close").click();
    await app.alerts.clickPrepBriefOnFirstRow();
    await app.meetingBrief.expectAutoGeneratedBrief();
    await captureScreenshot(page, "13-alerts-prep-brief-landing", testInfo);
  });

  test("full navigation includes Clients", async ({ app, page }, testInfo) => {
    await app.dashboard.goto();
    const routes = [
      "Clients",
      "AI Copilot",
      "Meeting Brief",
      "Alerts",
      "Ingestion",
      "Settings",
      "Dashboard",
    ] as const;
    for (const route of routes) {
      await app.shell.navigateTo(route);
      await page.waitForLoadState("domcontentloaded");
      await captureScreenshot(page, `14-nav-${route.toLowerCase().replace(/\s+/g, "-")}`, testInfo);
    }
  });
});
